name: Push

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Clone this repository

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh cmake
          sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly \
            && chmod +x /usr/local/bin/earthly \
            && /usr/local/bin/earthly bootstrap --with-autocomplete'

      - name: Test setup files
        run: ./test.sh

      - name: Test Lacework-specific setup files
        run: ./lacework_test.sh

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
