name: Push

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Clone this repository

      - name: Setup `zsh`
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - name: Test setup files
        run: ./test.sh
